default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sa
  password: Admin@123
  host: localhost
  port: 1433

development:
  <<: *default
  database: meu_sistema_development

test:
  <<: *default
  database: meu_sistema_test

production:
  <<: *default
  database: meu_sistema_production
